### ISSUE TITLE
Request title serialized incorrectly

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/drafter#219]
While moving [Aglio](https://github.com/danielgtaylor/aglio) over to using [Refract](https://github.com/refractproject/refract-spec) I ran into this fun issue. Sample minimal input (the problem remains when not using shortcuts also):

```apib
# GET /foo

+ Request Hello
```

Relevant piece of the output (from `./bin/drafter input.apib` on `master`):

```yaml
element: "httpRequest"
attributes:
  method: "GET"
  title: "Hello"
content: []
```

The problem is that [HTTP Message Payloads](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md#http-message-payload-element) don't have a `title` attribute. Correct serialization:

```yaml
element: "httpRequest"
meta:
  title: "Hello"
attributes:
  method: "GET"
content: []
```

Thanks! :cake:
