### ISSUE TITLE
Incorrectly parsed object sample

### ISSUE THREAD

**Issue by zdne** [apiaryio/drafter#246]
Following blueprint (MSON):

```apib
# Data Structures

## A
+ myArray (array)
    - A
    - B
    - myObject 
          - key1: value1
          - key2: value2 - Nested Object in Array description
```

Gets parsed without warning and `myObject` is considered as an object sample value (??!?)

```yaml
-
  element: "object"
  attributes:
    samples:
      -
        -
          element: "string"
          content: "myObject"
```

Instead the parser MUST warn about unexpected / unrecognized literals `myObject` and ignore them
