### ISSUE TITLE
Set default value to Infinity

### ISSUE THREAD

**Issue by Baggz** [apiaryio/drafter#251]
Hello,

I'm trying to set default value to Infinity...

```
* maxInheritanceDepth: 3 (number)
    * Default: Infinity
```

...but the Refract I'm getting is the following.

```
{
  "element":"member",
  "content":{
    "key":{
      "element":"string",
      "content":"maxInheritanceDepth"
    },
    "value":{
      "element":"number",
      "attributes":{
        "default":null
      },
      "content":3
    }
  }
}
```

You can see that `default` is set to `null`.

Is that an intended behaviour?

Thanks for the clarification!

**Comment by kylef** [comment]
I wasn't aware this was possible and it's not mentioned in the spec. However, I've tested this with the latest version of Drafter and it is exposing Infinity in both YAML and JSON outputs.

Here's a minimal blueprint to produce:

#### `blueprint.apib`

```apib
# API
## Data Structures
### Example

+ maxInheritnceDepth: 3 (number)
    * Default: Infinity
```

#### `$ drafter  blueprint.apib`

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: "API"
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Example"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "maxInheritnceDepth"
                      value:
                        element: "number"
                        attributes:
                          default: inf
                        content: 3
```

#### `$ drafter  blueprint.apib -f json`

```json
{
  "element": "parseResult",
  "content": [
    {
      "element": "category",
      "meta": {
        "classes": [
          "api"
        ],
        "title": "API"
      },
      "content": [
        {
          "element": "category",
          "meta": {
            "classes": [
              "dataStructures"
            ]
          },
          "content": [
            {
              "element": "dataStructure",
              "content": [
                {
                  "element": "object",
                  "meta": {
                    "id": "Example"
                  },
                  "content": [
                    {
                      "element": "member",
                      "content": {
                        "key": {
                          "element": "string",
                          "content": "maxInheritnceDepth"
                        },
                        "value": {
                          "element": "number",
                          "attributes": {
                            "default": inf
                          },
                          "content": 3
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

It would seem the problem is further down the line, either in Protagonist or Plutonium. Since it would seem that [JSON.stringify converts `Infinity` to `null`](http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null) which I know is done in Plutonium.
