### ISSUE TITLE
MSON Data Structure is not able to be referenced

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#253]
In the following blueprint, it's not possible to reference the data structure "Event" in any way.

```apib
# Test
## Resource [/]
### Action [GET]
+ Response 200 (application/json)
    + Attributes (Event)

## Data Structures
### Event
- name: Sent
- timeUtc: `Wed, 16 Mar 2016 22:29:50 GMT` (string)
```

This example produce the following warning:

```
warning: (8)  unable to find the symbol `Event` in the list of named types; line 5, column 7 - line 5, column 25
```

Here's the complete output from Drafter `v2.3.0-pre.0`.

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: "Test"
    content:
      -
        element: "category"
        meta:
          classes:
            - "resourceGroup"
          title: ""
        content:
          -
            element: "resource"
            meta:
              title: "Resource"
            attributes:
              href: "/"
            content:
              -
                element: "transition"
                meta:
                  title: "Action"
                content:
                  -
                    element: "httpTransaction"
                    content:
                      -
                        element: "httpRequest"
                        attributes:
                          method: "GET"
                        content: []
                      -
                        element: "httpResponse"
                        attributes:
                          statusCode: "200"
                          headers:
                            element: "httpHeaders"
                            content:
                              -
                                element: "member"
                                content:
                                  key:
                                    element: "string"
                                    content: "Content-Type"
                                  value:
                                    element: "string"
                                    content: "application/json"
                        content:
                          -
                            element: "dataStructure"
                            content:
                              -
                                element: "Event"
                          -
                            element: "asset"
                            meta:
                              classes:
                                - "messageBody"
                            attributes:
                              contentType: "application/json"
                            content: "{}"
                          -
                            element: "asset"
                            meta:
                              classes:
                                - "messageBodySchema"
                            attributes:
                              contentType: "application/schema+json"
                            content: "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {}\n}"
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: " Event"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "name"
                      value:
                        element: "string"
                        content: "Sent"
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "timeUtc"
                      value:
                        element: "string"
                        content: "Wed, 16 Mar 2016 22:29:50 GMT"
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 8
      sourceMap:
        -
          element: "sourceMap"
          content:
            -
              - 80
              - 19
    content: "unable to find the symbol `Event` in the list of named types"

```
