### ISSUE TITLE
Using mixins when the referenced object inherits from another object fails

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#254]
When using a mixin via "Include" where the mixin has a parent type (other than directly object) the `Mixin must refer to same type as parent` warning is thrown.

#### Example blueprint to reproduce

```apib
# API
## Resource [/]
### Action [GET]

+ Response 200 (application/json)
    + Attributes
        + Include Example

## Data Structures
### Example (Other)
### Other
```

Note, changing the following would prevent this warning.

```diff
- ### Example (Other)
+ ### Example
```

Drafter `v2.3.0-pre.0` output:

```yaml
element: "parseResult"
content:
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 4
      sourceMap:
        -
          element: "sourceMap"
          content: []
    content: "Mixin must refer to same type as parent"
```
