### ISSUE TITLE
Certain warnings are being treated as errors

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#255]
I'm not sure what the correct behaviour is here. We are raising some "warnings" in parse results, however these are being treated as errors since the parse result doesn't contain other content.

You can find examples of this in both #252 and #254.

```yaml
element: "parseResult"
content:
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 4
      sourceMap:
        -
          element: "sourceMap"
          content: []
    content: "no property name"
```

The solution is that these warnings should actually be errors, or other content (API name, etc) should be in the parse result.

**Comment by kylef** [comment]
To reproduce currently:

```apib
# API
## Resource [/]
### Action [GET]

+ Response 200 (application/json)
    + Attributes
        + Include Example

## Data Structures
### Example (Other)
### Other
```

---

```yaml
element: "parseResult"
content:
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 1
      sourceMap:
        -
          element: "sourceMap"
          content:
            -
              - 42
              - 32
    content: "Mixin must refer to same type as parent"
```
