### ISSUE TITLE
Numbers values are always zero

### ISSUE THREAD

**Issue by lkraider** [apiaryio/drafter#334]
For:
```
drafter --version
v2.1.1
```

Given the following input:
```
# Data Structures
## Crop
+ x: ​5 (number)
+ y: ​10 (number)
+ w: ​625 (number)
+ h: ​500 (number)
```

The values content for the numbers are always zero after parsing:
```
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: ""
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Crop"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "x"
                      value:
                        element: "number"
                        content: 0
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "y"
                      value:
                        element: "number"
                        content: 0
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "w"
                      value:
                        element: "number"
                        content: 0
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "h"
                      value:
                        element: "number"
                        content: 0
```
