### ISSUE TITLE
Escaped values in MSON are treated as markdown

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#365]
Given the following API Blueprint.

```apib
# Data Structures
## Example
+ example: `__main__`
```

or

```apib
# Data Structures
## Example
+ example: `*main*`
```

Drafter 2.3.1 will output the following parse result:

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: ""
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Example"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "example"
                      value:
                        element: "string"
                        attributes:
                          samples:
                            - "main"
```

Note, my sample value is converted from `__main__` or `*main*` to `main`.

#### Expected result

My sample value is `__main__` in the parse result.

#### Actual Result

My escaped sample value is shown as intended within the parse result.
