### ISSUE TITLE
Allow type attributes in Mixins

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#370]
`fixed`, `required` and `optional` are allowed for mixin definitions.

# Input
```apib
# Data Structures
# A 
+ a: a

# B
+ b: b
+ Include (A, optional)
```

# Output
```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: ""
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "A"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "a"
                      value:
                        element: "string"
                        content: "a"
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "B"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "b"
                      value:
                        element: "string"
                        content: "b"
                  -
                    element: "ref"
                    content:
                      href: "A"
                      path: "content"
```

# Expected
There should `typeAttributes: ["optional"]` somewhere in there.
