### ISSUE TITLE
Large numbers are being truncated

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#443]
```apib
# GET /

+ Parameters
    + example: 421795144078094336 (number, options)

+ Response 204

```

Drafter Output:

```yaml
                        content:
                          key:
                            element: "string"
                            content: "example"
                          value:
                            element: "number"
                            content: 4.21795e+17
```

The value `4.21795e+17` is rendered as `421795144078094340 ` which is not the same as `421795144078094336 `.

The value in API Blueprint AST is `421795144078094336`.

NOTE: This applies to number in MSON and Number Parameters in API Elements.
