### ISSUE TITLE
URI Template without leading slash doesn't get recognized

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#459]
Given following API Blueprint

```apib
FORMAT: 1A

# Cats API

# User Authentication [GET v6/auth]

Logins an a user and gives them an accesss token

+ Request (application/json)

        {
            "username": "test.user@foodpanda.com",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            "access_token": "RandomStringForAuth"
        }
```

I get following output from Drafter:

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: "Cats API"
    attributes:
      meta:
        -
          element: "member"
          meta:
            classes:
              - "user"
          content:
            key:
              element: "string"
              content: "FORMAT"
            value:
              element: "string"
              content: "1A"
    content:
      -
        element: "copy"
        content: "# User Authentication [GET v6/auth]\n\nLogins an a user and gives them an accesss token\n\n+ Request (application/json)\n\n        {\n            \"username\": \"test.user@foodpanda.com\",\n            \"password\": \"test\"\n        }\n\n+ Response 200 (application/json)\n\n        {\n            \"access_token\": \"RandomStringForAuth\"\n        }"
```

Drafter completely ignores the `User Authentication [GET v6/auth]` section. This isn't very user-friendly. It's quite clear user just forgot to start the URI Template with a leading slash character. Drafter should be able to read such markup with a warning.

This is a follow-up to a real, user-reported developer experience glitch: https://github.com/apiaryio/dredd/issues/261
