### ISSUE TITLE
Non-functional reference-style links

### ISSUE THREAD

**Issue by abtris** [apiaryio/drafter#623]
@zdne opened apiaryio/snowcrash#55

Update: This is no longer the issue, however there is still a problem when the reference is defined in another description block. See https://github.com/apiaryio/snowcrash/issues/55#issuecomment-58488125

---

~~Following blueprint:~~

```
# API
This is [an example][id] reference-style link.

[id]: http://example.com "x"
```

~~renders as:~~

``` yaml
_version: 1.0
metadata:
name: API
description: "This is [an example][id] reference-style link.\n\n["
resourceGroups:

```

Refer to Markdown [Link Syntax](http://daringfireball.net/projects/markdown/syntax#link)
