### ISSUE TITLE
Underscore in parameter key and value will cause parse incorrect

### ISSUE THREAD

**Issue by othree** [apiaryio/drafter#697]
Hi

This is what I am writing:

```apib
FORMAT: 1A

# Merchant Dashboard

## Data Structures

### Report
+ payment_id: pay_123456 (string, required)
```

And execute drafter will got(part of output):

```
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Report"
                content:
                  -
                    element: "member"
                    attributes:
                      typeAttributes:
                        - "required"
                    content:
                      key:
                        element: "string"
                        content: "payment_id: pay_123456"
                      value:
                        element: "string"
```

The key is parsed as `payment_id: pay_123456`.

But if I remove the `_` in the key:

```apib
FORMAT: 1A

# Merchant Dashboard

## Data Structures

### Report
+ paymentid: pay_123456 (string, required)

```

The result is correct:

```
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Report"
                content:
                  -
                    element: "member"
                    attributes:
                      typeAttributes:
                        - "required"
                    content:
                      key:
                        element: "string"
                        content: "paymentid"
                      value:
                        element: "string"
                        content: "pay_123456"
```

I try add `\` before `_` to escape. But doesn't work.
